//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCall.ServiceReferenceDB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDB.WebService4Soap")]
    public interface WebService4Soap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  ap_sqlno 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Title", ReplyAction="*")]
        WebServiceCall.ServiceReferenceDB.Get_TitleResponse Get_Title(WebServiceCall.ServiceReferenceDB.Get_TitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Title", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceDB.Get_TitleResponse> Get_TitleAsync(WebServiceCall.ServiceReferenceDB.Get_TitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_TitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Title", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReferenceDB.Get_TitleRequestBody Body;
        
        public Get_TitleRequest() {
        }
        
        public Get_TitleRequest(WebServiceCall.ServiceReferenceDB.Get_TitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_TitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ap_sqlno;
        
        public Get_TitleRequestBody() {
        }
        
        public Get_TitleRequestBody(string ap_sqlno) {
            this.ap_sqlno = ap_sqlno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_TitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_TitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReferenceDB.Get_TitleResponseBody Body;
        
        public Get_TitleResponse() {
        }
        
        public Get_TitleResponse(WebServiceCall.ServiceReferenceDB.Get_TitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_TitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_TitleResult;
        
        public Get_TitleResponseBody() {
        }
        
        public Get_TitleResponseBody(string Get_TitleResult) {
            this.Get_TitleResult = Get_TitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService4SoapChannel : WebServiceCall.ServiceReferenceDB.WebService4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService4SoapClient : System.ServiceModel.ClientBase<WebServiceCall.ServiceReferenceDB.WebService4Soap>, WebServiceCall.ServiceReferenceDB.WebService4Soap {
        
        public WebService4SoapClient() {
        }
        
        public WebService4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCall.ServiceReferenceDB.Get_TitleResponse WebServiceCall.ServiceReferenceDB.WebService4Soap.Get_Title(WebServiceCall.ServiceReferenceDB.Get_TitleRequest request) {
            return base.Channel.Get_Title(request);
        }
        
        public string Get_Title(string ap_sqlno) {
            WebServiceCall.ServiceReferenceDB.Get_TitleRequest inValue = new WebServiceCall.ServiceReferenceDB.Get_TitleRequest();
            inValue.Body = new WebServiceCall.ServiceReferenceDB.Get_TitleRequestBody();
            inValue.Body.ap_sqlno = ap_sqlno;
            WebServiceCall.ServiceReferenceDB.Get_TitleResponse retVal = ((WebServiceCall.ServiceReferenceDB.WebService4Soap)(this)).Get_Title(inValue);
            return retVal.Body.Get_TitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceDB.Get_TitleResponse> WebServiceCall.ServiceReferenceDB.WebService4Soap.Get_TitleAsync(WebServiceCall.ServiceReferenceDB.Get_TitleRequest request) {
            return base.Channel.Get_TitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceDB.Get_TitleResponse> Get_TitleAsync(string ap_sqlno) {
            WebServiceCall.ServiceReferenceDB.Get_TitleRequest inValue = new WebServiceCall.ServiceReferenceDB.Get_TitleRequest();
            inValue.Body = new WebServiceCall.ServiceReferenceDB.Get_TitleRequestBody();
            inValue.Body.ap_sqlno = ap_sqlno;
            return ((WebServiceCall.ServiceReferenceDB.WebService4Soap)(this)).Get_TitleAsync(inValue);
        }
    }
}
