//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCall.ServiceReferenceFile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFile.WebServiceFileSoap")]
    public interface WebServiceFileSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  fs 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        WebServiceCall.ServiceReferenceFile.UploadFileResponse UploadFile(WebServiceCall.ServiceReferenceFile.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceFile.UploadFileResponse> UploadFileAsync(WebServiceCall.ServiceReferenceFile.UploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReferenceFile.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(WebServiceCall.ServiceReferenceFile.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] fs, string fileName) {
            this.fs = fs;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReferenceFile.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(WebServiceCall.ServiceReferenceFile.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFileSoapChannel : WebServiceCall.ServiceReferenceFile.WebServiceFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFileSoapClient : System.ServiceModel.ClientBase<WebServiceCall.ServiceReferenceFile.WebServiceFileSoap>, WebServiceCall.ServiceReferenceFile.WebServiceFileSoap {
        
        public WebServiceFileSoapClient() {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCall.ServiceReferenceFile.UploadFileResponse WebServiceCall.ServiceReferenceFile.WebServiceFileSoap.UploadFile(WebServiceCall.ServiceReferenceFile.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] fs, string fileName) {
            WebServiceCall.ServiceReferenceFile.UploadFileRequest inValue = new WebServiceCall.ServiceReferenceFile.UploadFileRequest();
            inValue.Body = new WebServiceCall.ServiceReferenceFile.UploadFileRequestBody();
            inValue.Body.fs = fs;
            inValue.Body.fileName = fileName;
            WebServiceCall.ServiceReferenceFile.UploadFileResponse retVal = ((WebServiceCall.ServiceReferenceFile.WebServiceFileSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceFile.UploadFileResponse> WebServiceCall.ServiceReferenceFile.WebServiceFileSoap.UploadFileAsync(WebServiceCall.ServiceReferenceFile.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCall.ServiceReferenceFile.UploadFileResponse> UploadFileAsync(byte[] fs, string fileName) {
            WebServiceCall.ServiceReferenceFile.UploadFileRequest inValue = new WebServiceCall.ServiceReferenceFile.UploadFileRequest();
            inValue.Body = new WebServiceCall.ServiceReferenceFile.UploadFileRequestBody();
            inValue.Body.fs = fs;
            inValue.Body.fileName = fileName;
            return ((WebServiceCall.ServiceReferenceFile.WebServiceFileSoap)(this)).UploadFileAsync(inValue);
        }
    }
}
