//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCall.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceCall.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceCall.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceCall.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  a 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/teach", ReplyAction="*")]
        WebServiceCall.ServiceReference1.teachResponse teach(WebServiceCall.ServiceReference1.teachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/teach", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.teachResponse> teachAsync(WebServiceCall.ServiceReference1.teachRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceCall.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceCall.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class teachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="teach", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReference1.teachRequestBody Body;
        
        public teachRequest() {
        }
        
        public teachRequest(WebServiceCall.ServiceReference1.teachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class teachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string b;
        
        public teachRequestBody() {
        }
        
        public teachRequestBody(string a, string b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class teachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="teachResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceCall.ServiceReference1.teachResponseBody Body;
        
        public teachResponse() {
        }
        
        public teachResponse(WebServiceCall.ServiceReference1.teachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class teachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string teachResult;
        
        public teachResponseBody() {
        }
        
        public teachResponseBody(string teachResult) {
            this.teachResult = teachResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServiceCall.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServiceCall.ServiceReference1.WebService1Soap>, WebServiceCall.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCall.ServiceReference1.HelloWorldResponse WebServiceCall.ServiceReference1.WebService1Soap.HelloWorld(WebServiceCall.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceCall.ServiceReference1.HelloWorldRequest inValue = new WebServiceCall.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceCall.ServiceReference1.HelloWorldRequestBody();
            WebServiceCall.ServiceReference1.HelloWorldResponse retVal = ((WebServiceCall.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.HelloWorldResponse> WebServiceCall.ServiceReference1.WebService1Soap.HelloWorldAsync(WebServiceCall.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServiceCall.ServiceReference1.HelloWorldRequest inValue = new WebServiceCall.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceCall.ServiceReference1.HelloWorldRequestBody();
            return ((WebServiceCall.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCall.ServiceReference1.teachResponse WebServiceCall.ServiceReference1.WebService1Soap.teach(WebServiceCall.ServiceReference1.teachRequest request) {
            return base.Channel.teach(request);
        }
        
        public string teach(string a, string b) {
            WebServiceCall.ServiceReference1.teachRequest inValue = new WebServiceCall.ServiceReference1.teachRequest();
            inValue.Body = new WebServiceCall.ServiceReference1.teachRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            WebServiceCall.ServiceReference1.teachResponse retVal = ((WebServiceCall.ServiceReference1.WebService1Soap)(this)).teach(inValue);
            return retVal.Body.teachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.teachResponse> WebServiceCall.ServiceReference1.WebService1Soap.teachAsync(WebServiceCall.ServiceReference1.teachRequest request) {
            return base.Channel.teachAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCall.ServiceReference1.teachResponse> teachAsync(string a, string b) {
            WebServiceCall.ServiceReference1.teachRequest inValue = new WebServiceCall.ServiceReference1.teachRequest();
            inValue.Body = new WebServiceCall.ServiceReference1.teachRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((WebServiceCall.ServiceReference1.WebService1Soap)(this)).teachAsync(inValue);
        }
    }
}
